import { createElement } from 'react';
import {
  Award,
  Baby,
  Banknote,
  BarChart3,
  BriefcaseBusiness,
  BusFront,
  Car,
  Dumbbell,
  Fuel,
  Gamepad2,
  GraduationCap,
  HandHeart,
  HeartPulse,
  House,
  MessageCircle,
  MoreHorizontal,
  PawPrint,
  Popcorn,
  Receipt,
  ReceiptText,
  RotateCcw,
  Shirt,
  ShoppingBasket,
  Smartphone,
  SlidersHorizontal,
  Sparkles,
  Tag,
  TrendingUp,
  Utensils,
  Users,
  Wallet,
  Wifi,
} from 'lucide-react';

export const CATEGORY_ICONS = {
  child_baby: Baby,
  fuel: Fuel,
  groceries: ShoppingBasket,
  donation: HandHeart,
  electronics: Smartphone,
  game: Gamepad2,
  entertainment_subscription: Popcorn,
  internet_phone: Wifi,
  investment_expense: BarChart3,
  family: Users,
  vehicle: Car,
  work: BriefcaseBusiness,
  health: HeartPulse,
  correction_expense: SlidersHorizontal,
  other_expense: MoreHorizontal,
  dining_out: Utensils,
  sports: Dumbbell,
  tax_admin: ReceiptText,
  clothing: Shirt,
  pet: PawPrint,
  education: GraduationCap,
  personal_care: Sparkles,
  household: House,
  social: MessageCircle,
  bills: Receipt,
  transport: BusFront,
  bonus: Award,
  salary: Wallet,
  investment_income: TrendingUp,
  grant: HandHeart,
  sale: Tag,
  correction_income: SlidersHorizontal,
  other_income: MoreHorizontal,
  refund: RotateCcw,
  side_income: Banknote,
  rent_income: House,
};

export const getCategoryIcon = (categoryId) =>
  createElement(CATEGORY_ICONS[categoryId] || MoreHorizontal, { size: 18, strokeWidth: 2 });
